// Copyright 2025 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'dart:io' as io;
import 'package:test/test.dart';
import 'package:git_repo_wiki_generator/json_to_markdown.dart';

void main() {
  group('convertJsonlToMarkdown', () {
    late io.Directory tempDir;

    setUp(() {
      tempDir = io.Directory.systemTemp.createTempSync(
        'json_to_markdown_test_',
      );
    });

    tearDown(() {
      if (tempDir.existsSync()) {
        tempDir.deleteSync(recursive: true);
      }
    });

    test(
      'creates markdown files from a jsonl file using sha as filename',
      () async {
        final jsonlFile = io.File('${tempDir.path}/input.jsonl');
        jsonlFile.writeAsStringSync('''
{"sha": "abcdef123", "commit": {"message": "Initial commit", "author": {"name": "Bob"}}}
{"sha": "987654fed", "commit": {"message": "Fix bug", "author": {"name": "Alice"}}}
''');

        final outputDir = io.Directory('${tempDir.path}/output');

        await convertJsonlToMarkdown(jsonlFile, outputDir);

        expect(outputDir.existsSync(), isTrue);

        final file1 = io.File('${outputDir.path}/abcdef123.md');
        final file2 = io.File('${outputDir.path}/987654fed.md');

        expect(file1.existsSync(), isTrue);
        expect(file2.existsSync(), isTrue);

        final content1 = file1.readAsStringSync();
        final content2 = file2.readAsStringSync();

        // Validate some of the markdown formatting generated by jsonObjectToMarkdown
        expect(content1, contains('commit'));
        expect(content1, contains('message'));
        expect(content1, contains('Initial commit'));
        expect(content2, contains('Fix bug'));
      },
    );

    test('falls back to index counter when sha is missing', () async {
      final jsonlFile = io.File('${tempDir.path}/input_no_sha.jsonl');
      jsonlFile.writeAsStringSync('''
{"commit": {"message": "No sha 1"}}
{"commit": {"message": "No sha 2"}}
''');

      final outputDir = io.Directory('${tempDir.path}/output_no_sha');

      await convertJsonlToMarkdown(jsonlFile, outputDir);

      final file1 = io.File('${outputDir.path}/0.md');
      final file2 = io.File('${outputDir.path}/1.md');

      expect(file1.existsSync(), isTrue);
      expect(file2.existsSync(), isTrue);

      expect(file1.readAsStringSync(), contains('No sha 1'));
      expect(file2.readAsStringSync(), contains('No sha 2'));
    });

    test('respects includeFilter when converting', () async {
      final jsonlFile = io.File('${tempDir.path}/input_filtered.jsonl');
      jsonlFile.writeAsStringSync('''
{"sha": "hash123", "commit": {"message": "Test filter", "extra_field": "hidden"}}
''');

      final outputDir = io.Directory('${tempDir.path}/output_filtered');

      await convertJsonlToMarkdown(
        jsonlFile,
        outputDir,
        includeFilter: ['.commit.message'],
      );

      final file = io.File('${outputDir.path}/hash123.md');
      expect(file.existsSync(), isTrue);

      final content = file.readAsStringSync();
      expect(content, contains('message'));
      expect(content, contains('Test filter'));
      expect(content, isNot(contains('extra_field')));
      expect(content, isNot(contains('hidden')));
    });
  });

  group('bin/json_to_markdown.dart CLI', () {
    late io.Directory tempDir;

    setUp(() {
      tempDir = io.Directory.systemTemp.createTempSync(
        'json_to_markdown_cli_test_',
      );
    });

    tearDown(() {
      if (tempDir.existsSync()) {
        tempDir.deleteSync(recursive: true);
      }
    });

    test('CLI converts multiple jsonl files successfully', () async {
      final jsonlFile1 = io.File('${tempDir.path}/cli_input1.jsonl');
      jsonlFile1.writeAsStringSync(
        '{"sha": "hashA", "commit": {"message": "CLI 1"}}\n',
      );

      final jsonlFile2 = io.File('${tempDir.path}/cli_input2.jsonl');
      jsonlFile2.writeAsStringSync(
        '{"sha": "hashB", "commit": {"message": "CLI 2"}}\n',
      );

      final outputDir = io.Directory('${tempDir.path}/cli_output');

      final result = await io.Process.run('dart', [
        'bin/json_to_markdown.dart',
        '-d',
        outputDir.path,
        jsonlFile1.path,
        jsonlFile2.path,
      ]);

      expect(result.exitCode, equals(0));
      expect(outputDir.existsSync(), isTrue);
      expect(io.File('${outputDir.path}/hashA.md').existsSync(), isTrue);
      expect(io.File('${outputDir.path}/hashB.md').existsSync(), isTrue);
    });
  });
}
